name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      
      - name: libsunwait
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          make package

      - name: archive results mac
        if: runner.os !='Linux' 
        uses: actions/upload-artifact@v1
        with:
          name: libsunwait-1.0.0-${{ matrix.os }}
          path: build/sunwait-1.0.0-Darwin.tar.gz

      - name: archive results linux
        if:  runner.os =='Linux' 
        uses: actions/upload-artifact@v1
        with:
          name: libsunwait-1.0.0-${{ matrix.os }}
          path: build/sunwait-1.0.0-${{ runner.os }}.tar.gz
 